node {
 
 stage('Git CheckOut') {
    git branch: 'main', url: 'https://github.com/anooprbelur/DevOps301_CaseStudy3_Assignment.git'
 }
 
 def project_path="Jenkins/petclinic-code"
 
 dir(project_path) {
 
 stage('Maven Clean') {
    sh 'mvn clean'
 }
 
  stage('Maven Compile') {
    sh 'mvn compile'
 }
 
 stage('Maven Testing') {
    sh 'mvn test'
 }
 
 stage('Maven Package') {
    sh 'mvn package'
 }
 
 stage('Archive Artifacts') {
    archive 'target/*.war'
 }
 
 
  stage('Archive into Artifactory') {
rtUpload (
    serverId: '1',
    spec: '''{
          "files": [
            {
              "pattern": "**/*.war",
			  "target": "generic-snapshot/"
              
            }
         ]
    }''',
 
    buildName: 'petclinic',
    buildNumber: '1'
)
}
 

 stage('Getting Ready For Ansible') {
    sh 'cp -rf target/*.war ../../Ansible/Tomcat/files/'
    sh "echo '<h1> Task Build ID: ${env.BUILD_DISPLAY_NAME}</h1>' > ../../Ansible/Tomcat/files/jenkins.html"
 }
  
 }

 def project_ansible="Ansible/Tomcat/"
 dir(project_ansible){
  
 stage('Ansible Deployment') {
    sh 'ansible-playbook webserver.yaml'
 }

 }
 
}






